default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: br_admin_development

test:
  <<: *default
  database: br_admin_test

production:
  <<: *default
  database: br_admin_production
  username: <%= ENV["BR_ADMIN_DB_USER"] %>
  password: <%= ENV["BR_ADMIN_DATABASE_PASSWORD"] %>
